title: "CRITICA ALGORITHMI"
description: "Critical Scrutiny of the Applications and Implications of Algorithms in the Humanities"
remote_theme: daattali/beautiful-jekyll
plugins:
- jekyll-remote-theme
